### ISSUE TITLE
Example Sarif Files

### ISSUE THREAD

**Issue by brentshermana** [Microsoft/sarif-vscode-extension#138]
The version of this plugin that is currently available in VSCode supports version 2.0.0-csd.2.beta.2019-01-09 of the sarif spec. I have been having problems getting some manually written sarif to be processed correctly, but my specific issues probably won't be helpful for others, especially considering that the sarif spec is quickly evolving.

My main thoughts were that it would make sense to include some basic `.sarif` examples that the plugin is currently confirmed to work with in this repository. I think that could help people get started using this plugin more easily.

**Comment by rscrivens** [comment]
This is a good suggestion. I'll pull over a couple of the test sarif files from the sdk that match the currently supported sarif version.
