### ISSUE TITLE
FileMapper does not handle uriBaseId pointing to a file share

### ISSUE THREAD

**Issue by timhermann** [microsoft/sarif-vscode-extension#152]
I created a sarif file from a scan of a network share. A sample originalUriBaseIds and artifact location follow:

```
"originalUriBaseIds": {
  "SRCROOT": {
    "uri": "file://hostName/shareName/folder/"
  }
}
...……...
{
  "location": {
    "uri": "nested/path/to/file.ext",
    "uriBaseId": "SRCROOT"
  }
},
```

Expected: File is attempted to be opened from the network share specified by hostName/shareName

Actual: FileMapper opens the "Sarif Result Location Remapping" dialog and has to be manually browsed to the network share path. The location that it appears to be trying to access is `\hostname\shareName\nested\path\to\file.ext`, rather than `\\hostname\shareName\nested\path\to\file.ext`

**Comment by rscrivens** [comment]
this should be fixed in the latest update 2.12.0 .
