### ISSUE TITLE
Failure to open 2.1.0 log files with restarting VS code

### ISSUE THREAD

**Issue by lukecartey** [microsoft/sarif-vscode-extension#162]
With the latest release (2.12.0) I get the following error message when trying to open 2.1.0 SARIF files, such as the `Comprehensive.sarif` sample in the repository:

![image](https://user-images.githubusercontent.com/5377966/57634201-c01d3b80-759c-11e9-8ab7-d613906be78f.png)

**Comment by rscrivens** [comment]
Thanks for reporting this issue Luke. Did you try opening a new VSCode instance? For me after the update was installed it still have the old extension loaded in the running vscode instance but on closing and reopening the new instance had the correct version installed and was able to load the comprehensive.sarif 2.1.0 file.

**Comment by lukecartey** [comment]
Thanks, restarting the VS Code instance worked.

Is it the normal workflow to require VS Code to restart before an extension update is applied? I thought VS Code extension updates were normally applied immediately (hence my confusion).

**Comment by rscrivens** [comment]
just tried the latest update, and after it installed I clicked the reload button on the extension details page and it reloaded the extension correctly. If you find clicking the reload button doesn't fix it, reopen and I can try to investigate more.
