### ISSUE TITLE
Extension fails to load SARIF files without $schema property

### ISSUE THREAD

**Issue by lukecartey** [microsoft/sarif-vscode-extension#168]
The specification says:

> A sarifLog object MAY contain a property named $schema 

However, if I try to load a SARIF file without the `$schema` property set, the SARIF explorer window crashes, on this line:

https://github.com/microsoft/sarif-vscode-extension/blob/master/src/FileConverter.ts#L315

**Comment by rscrivens** [comment]
good catch, I'll add a fix to only use it if it exists

**Comment by rscrivens** [comment]
This should be fixed in the latest update 2.13.1
