### ISSUE TITLE
Cannot load SARIF files with $schema set from sarif-spec github repo

### ISSUE THREAD

**Issue by lukecartey** [microsoft/sarif-vscode-extension#169]
The specification recommends the following location be used as the value for the `$schema` property:

https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json

However, the VS Code extension refuses to load SARIF files with this set as the schema property, reporting that:

"Sarif version '2.1.0' is not yet supported"

This is due to the way the extension tries to verify whether the SARIF file is of the appropriate type. It first checks the `version` property, then, if that is equal to the expected version, it parses the _file name_ of the given schema file to find a version string, and checks that against the name of the expected schema file.

Unfortunately, there's a bug in the parsing of the version from the schema name, so parsing the github schema URL will produce the following "version":

"schema-2.1.0"

As the "expected" schema file is:
http://json.schemastore.org/sarif-2.1.0-rtm.1

It therefore compares "2.1.0-rtm.1" against "schema-2.1.0", and aborts because it doesn't believe that you can convert "schema-2.1.0" to "2.1.0-rtm.1".

My suggestion would be to avoid parsing the name of the schema file at all - just use the `version` property in the SARIF file, which should uniquely define a particular SARIF version. If extra validation is required, you can compare the given schema file with the expected schema file using structural equality (to verify that it is an equivalent schema).

**Comment by rscrivens** [comment]
This should be fixed in the newest update 2.13.1
