### ISSUE TITLE
On Linux, run dotnet Sarif.Multitool instead of Sarif.Multitool.exe

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#199]
A customer running the VS Code SARIF Viewer extension on Kubuntu attempted to open a Clang plist file (which he had renamed to .xml). He got this error on the developer tools console:

```
ERR spawn MYPATH/.vscode/extensions/ms-sarifvscode.sarif-viewer-2.14.0/resources/sarif.multitool/Sarif.Multitool.exe EACCES: Error: spawn MYPATH/.vscode/extensions/ms-sarifvscode.sarif-viewer-2.14.0/resources/sarif.multitool/Sarif.Multitool.exe EACCES
at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
at onErrorNT (internal/child_process.js:407:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

The problem is that the viewer always invokes `Sarif.Multitool.exe` for conversion, but on Linux it should invoke `dotnet Sarif.Multitool`.

**Comment by lgolding** [comment]
@LambdaScientist-1stEdge

As a workaround, you can try this:

1. If you don't already have it, install the [.NET Core SDK](https://aka.ms/dotnetcoregs), which includes the `dotnet` command line tool.

1. Install the `Sarif.Multitool` tool package from NuGet:
```
dotnet tool install --global Sarif.Multitool
```

3. Run the command
```
sarif convert --tool ClangAnalyzer myfile.plist --output myfile.sarif
```

4. Open `myfile.sarif` directly in VS Code.

**Comment by GabeDeBacker** [comment]
@lgolding - As of pull request #216 this issue should be fixed in the master branch.
