### ISSUE TITLE
File open dialog for conversion restricts filename extension

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#200]
1. Press F1. The Command Palette opens.

2. Type `sarif:Convert and open a non-sarif file`. (It will auto-complete after a few characters). A list of supported tools appears.

3. Select `ClangAnalyzer`. The Open File dialog opens.

![image](https://user-images.githubusercontent.com/11762653/64214317-e4ab6500-ce64-11e9-9c78-ac35953c3b56.png)

Note that the filter dropdown only offers one option: `ClangAnalyzer log files (*.xml)`. It should also have an option `All files (*.*)` in case the file has a different extension, like `.plist`.

You _can_ open files with other extensions, but you have to type the filename by hand because it won't appear in the files list.

I saw this on Windows. I don't know if it happens on Linux.

I haven't checked to see if the Open File dialogs for the other tools have the same problem, but we should make sure they all offer `*.*`.

@LambdaScientist-1stEdge @michaelcfanning FYI

**Comment by LambdaScientist-1stEdge** [comment]
Its happens on Linux as well.

**Comment by michaelcfanning** [comment]
@lgolding can we get this fixed? We need a change in the vs add-in as well, see clang analyzer filter data in the following file.

src\Sarif.Viewer.VisualStudio\OpenLogFileCommands.cs

**Comment by LambdaScientist-1stEdge** [comment]
@michaelcfanning In the mean time, will it work to just rename the plist files to xml?

**Comment by michaelcfanning** [comment]
I believe so, unless the plist file is emitted in a binary format that we're not covering (as a cursory internet search suggests it might). If you have a repro file that you can attach here (assuming there is a problem), that could be a leg up.

We're definitely committed to getting this scenario working. If we need additional support for some uncovered plist format, we'll make it happen.

**Comment by lgolding** [comment]
Yes, I'll fix this today.
