### ISSUE TITLE
'\' can not be found

### ISSUE THREAD

**Issue by samyun** [microsoft/sarif-vscode-extension#203]
Hello, I have a sarif v2.1.0 file that I'm trying to open. 

When I first opened it, the extension prompted me to remap a certain file, and I passed in the file path (d:\ada\src\{path}\{to}\{file.cpp}). 

Then it prompted me for the path to '\'. I have no idea what it might be asking for. Ignoring it seems to load the results. 

Is this something I should be worried about?

**Comment by jeffersonking** [comment]
@samyun  Thanks for your (2 year) patience. Version 3 (2020 Sep) now uses a standard file dialog for remapping files. Either way there will not be a secondary prompt. So essentially the answer is: no need to worry about it. Feel free to reopen if you are still running into issues. Thanks!
