### ISSUE TITLE
Unable to scroll inside the SARIF Explorer tab (Results list is too big)

### ISSUE THREAD

**Issue by rkkoszewski** [microsoft/sarif-vscode-extension#204]
Hi, 

I have over 2900 results in the Results List in the SARIF Explorer tab, so the list overflows as expected with so many results. But there is no scrollbar in the SARIF Explorer view, using the mouse scroller does not have any effect eider and keyboard navigation doesn't seem to be supported eider. 

I don't see any exception messages showing up anywhere during the parsing of the sarif file, so I assume that the plugin is working correctly for most of it.

Is there some way to be enable scrolling in the SARIF Explorer view? If this is a bug how can I help out to debug this? (As I don't see any exceptions showing up anywhere)

**Comment by BastienFaure** [comment]
Is there any plan to fix this issue in the next days/weeks ? I can work on a fix if nobody is assigned to that task.

**Comment by BastienFaure** [comment]
Is this project... dead ?

**Comment by michaelcfanning** [comment]
This project was not dead, merely dormant. :) We'll get this taken care of.
