### ISSUE TITLE
Extension doesn't recognize rtm.5 schema

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#217]
Creating a new SARIF file by hand in VS Code:

![NewSarifFile](https://user-images.githubusercontent.com/11762653/78604872-57bbf600-780f-11ea-99b6-e4b3ee12da07.png)

I get this:

![SchemaNotRecognized](https://user-images.githubusercontent.com/11762653/78604915-702c1080-780f-11ea-8a55-368ddaa2c75e.png)

This URL validly points to the rtm.5 schema on schemastore.

**Comment by GabeDeBacker** [comment]
@lgolding - This is fixed in the master branch
