### ISSUE TITLE
The viewer gets very sluggish to use for big sarif files.

### ISSUE THREAD

**Issue by harleenkohli** [microsoft/sarif-vscode-extension#220]
We tried to open a file which 10000+ sarif results (14 MB). The load is slow and it is difficult to navigate file nodes in the viewer (e.g. when opening/closing per result expanders) or changing "group by" drop down.

![image](https://user-images.githubusercontent.com/23230747/78742119-fe87bb80-790f-11ea-995f-b149e87c2df0.png)

To repro this issue, please get the 10000 results file from Larry or me offline.

**Comment by jeffersonking** [comment]
I loaded a 10,000 result 25MB file using the latest version (v3.x). It opened within 1-2 seconds. Navigation was fine except if if a group has over 5000 results. This is also keeping in mind #375 which is being tracked separately. Altogether, this seems to be within the current design requirements.

If we need more perf, we can implement virtualized rendering.
