### ISSUE TITLE
The records in the "Results" viewer are reloaded every time we switch between opened files in VSCode.

### ISSUE THREAD

**Issue by harleenkohli** [microsoft/sarif-vscode-extension#221]
Repro steps:
1. Open a sarif file in VSCode extension. Allow it time to load properly in the viewer pane.
2. Open another file/window.
3. Rapidly switch between the two windows.

Notice that the records count becomes 0 for a short while in the sarif viewer pane. This issue is concerning specially when we are dealing with a huge sarif file since it takes significant time to load again.

![image](https://user-images.githubusercontent.com/23230747/78742828-e0bb5600-7911-11ea-9c56-6cccae8dd58e.png)

**Comment by jeffersonking** [comment]
This is no longer an issue since v3. In particular we enable `retainContextWhenHidden` on the panel, and also the performance is generally better.
