### ISSUE TITLE
There is no way to scroll down to "details" pane if all the available space in taken by "results" pane records.

### ISSUE THREAD

**Issue by harleenkohli** [microsoft/sarif-vscode-extension#222]
Typically, another "Details" pane is visible at the bottom of "results" pane which shows information when a specific record is selected in the "Results" pane. 

If there are a lot of records so that the whole "Results" pane is filled, there is no way to view the "Details" pane. Scrolling is not possible and nothing pops-up on the screen to view it.

We tried this with a file with 10000+ records. To repro, get this file from Larry or me.

**Comment by GabeDeBacker** [comment]
@harleenkohli - This should be addressed in the Insiders version at was fixed with PR #228
