### ISSUE TITLE
Viewer doesn't deal well with binary files

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#224]
1. Load the sample SARIF file [EmbbeddedBinaryContent.sarif](https://raw.githubusercontent.com/microsoft/sarif-samples/master/samples/EmbeddedBinaryContent.sarif).

2. Double-click on its single result.

Expected: Well, it's not clear what to expect here, because I don't know VS Code's facilities for displaying binary files.

Actual: It loads the 5-byte contents into a text editor window and displays squares for the bytes -- which I can't blame it for -- but it doesn't highlight anything, even though the result sepcifies a region with `byteOffset` of 2 and `byteLength` of 2.

**Comment by GabeDeBacker** [comment]
@lgolding - We have addressed this in the current Insiders version as well as the new UI @jeffersonking is working on.
