### ISSUE TITLE
Add Keyboard navigation of the CodeFlowLocations in the editor

### ISSUE THREAD

**Issue by rscrivens** [Microsoft/sarif-vscode-extension#23]
New feature to assign keys to navigate the codeflowlocations in the editor. A couple of initial design questions to discuss:
- Which keys will we assign to forward and backward navigation? Are there other actions we want?
- How should we handle when there is more then one CodeFlow in the result? Couple options I can think of:
   * cycle within one codeflow until you switch to  the next(either a keyboard key or mouse selection)
   * on reaching the end of the current codeflow the next hotkey will take you to the beginning of the next codeflow. In this scenario will it be obvious that they entered a different codeflow or do we need a notification of some sort?

**Comment by michaelcfanning** [comment]
This seems important to tackle in the short-term

**Comment by rscrivens** [comment]
I'm changing these two keybindings from F9 and F10 to Ctrl+F9 and Ctrl+F10. With the previous key mapping it was interfering with VSCodes default F9 command which adds a breakpoint to the current line in the editor.
