### ISSUE TITLE
Add CodeFlow/Stacks path decorations to the Editor

### ISSUE THREAD

**Issue by rscrivens** [Microsoft/sarif-vscode-extension#24]
New feature to give a better visualization in the editor of the code path of the result. We currently highlight the codeflow locations but we don't give any indication of the calls and call returns. 

The main pending issue for this feature is:
Sarif V2 CodeFlowLocations(v2's version of AnnotatedCodeLocation) no longer have a "kind" property. So the "call" or "callReturn" values are not available to determine when to put a decoration on the line. We could infer using the nesting levels but there's no guarantee that two codeflowlocations next to each other with different nesting levels are the call into or out of. All we know is that at some point after the first location and before the second location a call or return was made.

We could try using the Stacks object on the result to determine when to put a call decoration.

**Comment by dgmelski** [comment]
There are multiple decorations that are on my wishlist:

1. Showing multiple text description boxes in the code viewer. (Maybe this one is already there? We were only showing for the "current" view.)
2. Gutter icons for branches that show direction of branch. I believe we use a "value" field for this that is usually "true" or "false" but might have a numeric value for a switch.
3. Icons that indict entering or entering and returning from a function call. Maybe there should be an icon at the end of returning functions, too.

The original issue seems to focus just on the third point? Maybe we should split these into three separate issues?

**Comment by rscrivens** [comment]
Thanks, that's a good idea, I'll split these into three different feature requests.

**Comment by michaelcfanning** [comment]
Larry will take a close look at whether the new SARIF v2 can properly support these scenarios. Current SARIF seems particularly ill-suited to indicate branches taken.

If kind is readable string, perhaps we just add a new option for an image to represent the kind. Should we restore the notion of a 'target', which is a per-kind interpretation of an additional piece of data.

**Comment by rscrivens** [comment]
Here's a screenshot of the proposed Call and CallReturn icons feature on line 23 and 53 in the image, these are placed based off of the change in nestingLevel between two locations(if it increased we put a call icon on the first one, if it decreased we put a callReturn icon on the first one): 
![image](https://user-images.githubusercontent.com/34690530/40945290-ff53c484-680c-11e8-8336-9b50c72532e3.png)

Let me know if anyone has any feedback or suggestions?

**Comment by rscrivens** [comment]
Thanks for the feedback. Here's what I came up with based on your comments. Let me know what you think or if I missed anything:
VSCode debugger uses these two icons for step into/out of: 
![image](https://user-images.githubusercontent.com/34690530/41068369-fde2656e-699d-11e8-8a81-a0961679de7b.png)

So I pulled from those to create some new distinct icons for the 3 scenarios:
![image](https://user-images.githubusercontent.com/34690530/41069312-32cc1c1c-69a2-11e8-8be8-b65d8964946e.png)

Here are some example screenshots that I think cover the scenarios you mentioned:
1. 
![image](https://user-images.githubusercontent.com/34690530/41071203-78d98074-69ab-11e8-94ba-4c6b7a272d26.png)
2. 
![image](https://user-images.githubusercontent.com/34690530/41071460-a98c16ae-69ac-11e8-96cf-00d1b03b0c20.png)
3. 
![image](https://user-images.githubusercontent.com/34690530/41071368-27a53c10-69ac-11e8-8cf6-4ca36f0124d3.png)

* Note * scenario # 2: in the Sarif Explorer codeflow paneI I added a way to have a nested first step without a calling parent, that's what the row "Nested Call" is, but I'm thinking it might read better if I change it to something like "Nested first step"?

**Comment by rscrivens** [comment]
Updated the icons with feedback from Mike. Here's the latest:
![callicons](https://user-images.githubusercontent.com/34690530/41260085-e39084b6-6d8a-11e8-837c-9308e2e13f8a.png)
Screenshots of the new icons:
1.
![image](https://user-images.githubusercontent.com/34690530/41260189-466377ce-6d8b-11e8-8a77-70cf4d01b0a2.png)

2.
![image](https://user-images.githubusercontent.com/34690530/41260225-614667c2-6d8b-11e8-8331-aa76e6a8ca45.png)

3. 
![image](https://user-images.githubusercontent.com/34690530/41260137-1dac63a4-6d8b-11e8-9a1c-4880b48de49d.png)

**Comment by rscrivens** [comment]
Closing this issue as the feature has been checked in. Can open a new issue if we want to discuss improvements to the icons.
