### ISSUE TITLE
Consider decoupling progress UI from Log Reader

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-vscode-extension#240]
The SARIF log reader is currently driving VSCode's "withProgress" UI when parsing SARIF files.

The idea for this issue is to decouple that from the log-reader so the log-reader purely becomes a data model only piece of code. It can still have "progress" events, but it will be up to the consumer to handle and display them.

This would also remove the need for a singleton "progress helper" class.

**Comment by jeffersonking** [comment]
Since #348 we no longer have/need progress window. Thus closing.
