### ISSUE TITLE
Show the SARIF panel when opening a single SARIF file without a project

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#259]
As the code stands, when you open a folder, the extension finds all the SARIF files in the folder and displays the results in the SARIF pane. But when no folder is open and you open a SARIF file, the extension does not display the SARIF pane.

**Comment by jeffersonking** [comment]
Note: This is feedback for the new webview version.

**Comment by lgolding** [comment]
This behaves currently in the current version.
