### ISSUE TITLE
Consider adding an option to supress upgrade prompt.

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-vscode-extension#261]
When users open SARIF files directly, they are constantly getting asked to upgrade SARIF files with either Save (Temp) or Save (As).

We should consider adding an option that allows:
Prompt -> Prompts the user
UpgradeTemp-> Creates a temporary file
UpgradeInPlace -> Upgrades the SARIF in place.

**Comment by jeffersonking** [comment]
If we go this direction, would be good to with common pattern is to allow the user to [Don't Show Again...]. Which goes with Gabe's suggestion of saving to config.

We have a lot of choice buttons, so perhaps the first message should just have the options:
[Upgrade][Don't Show Again]

Note: The "No" option is handled by convention via the [x]. Aka the [No] is an anti-pattern.

Subsequent prompts can handle "save temp" "save as" and also "remember my choice for future...".
