### ISSUE TITLE
Results list clears after selecting an issue

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#262]
Repro:

1. In the file explorer pane, _single-click_ on a SARIF file to open it in preview.
    NOTE: For this to work, you must have the setting **Workbench** > **Editor**: **Enable preview** _set_.

2. In the SARIF pane, click on any result.

Expected:

The result file opens in a separate preview window, the SARIF file remains open, and the SARIF pane's results list remains populated.

Actual:

The result file opens in the same window as the SARIF file (effectively closing the previewed SARIF file), and the SARIF pane's results list clears.

You can avoid this problem either by opening the SARIF file with a double-click (which opens it as a "real" file rather than in preview) or by disabling the **Workbench** > **Editor**: **Enable preview** setting. For this reason, this bug (if so it is) might not be worth fixing. But if you don't understand how VS Code preview windows work, the observed behavior is confusing.

**Comment by jeffersonking** [comment]
This is addressed by v3. Specifically here: https://github.com/microsoft/sarif-vscode-extension/blob/3eb1e4fd6cf6237812100f170086e14affe289a5/src/extension/panel.ts#L155
