### ISSUE TITLE
Navigating to insertion point at end of file does not work

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#263]
[RegionVariants.sarif.txt](https://github.com/microsoft/sarif-vscode-extension/files/4525522/RegionVariants.sarif.txt)

**Repro steps:**

1. Open the attached SARIF file.

2. Click the _next-to-last_ result, which navigates to an insertion point at the end of the file, specified by line/column properties (`{ "startLine": 4, "startColumn": 6, "endColumn": 6 }`).
    An insertion point cursor appears after the last visible character on line 4.

3. Click the _last_ result, which also navigates to an insertion point at the end of the file, this time specified by charLength/charOffset properties: (`{ "charOffset": 22, "charLength": 0 }`).

**Expected:**

An insertion point cursor appears after the last visible character on line 4.

**Actual:**

An insertion point cursor appears after the last visible character on line 1.

**Comment by jeffersonking** [comment]
Revisiting this issue in the context of v3. The insertion point cursor no longer appears on line 1. However, it does not appear on line 4 either. It appears on line 5, which I believe is a more correct answer. The file ends with a newline, so at the EOF we should be on line 5, right?

We are strongly aligned with how VS Code interprets these region metrics. Deviation from VS Code would require an abstraction layer.
