### ISSUE TITLE
"Call trees" => "Code flows"

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#273]
In the details pain, the "Call trees" tab should be labeled "Code flows" (on the principle of "ubiquitous vocabulary") since that is the SARIF term.

**Comment by lgolding** [comment]
@michaelcfanning Do you agree?

**Comment by jeffersonking** [comment]
I noticed it's called "Call Trees" in the VS "Full" extension.

Also, isn't "Code Flows" confusing with regards to the code review tool of the same name?
________________________________

**Comment by michaelcfanning** [comment]
I think 'Code Flows' is probably good. Yes, I appreciate it is overloaded with the MS tooling. :) 

'Code Paths' might work as well. Note that I don't always think we should prefer the SARIF terminology we defined, as it is all-encompassing (across all tools and scenarios) which can sometimes compromise a term's clarity or descriptive value.

In this case, though, I think 'code flows' is actually useful given the VS Code utilization.

**Comment by lgolding** [comment]
@jeffersonking I filed the same bug against the Visual Studio extension. It should be "Code Flows" there as well.

**Comment by lgolding** [comment]
@michaelcfanning I agree that SARIF terminology is not always best. I've never recovered from "`reportingDescriptor`" instead of "`rule`", so I hear you loud and clear. As with any principle, "ubiquitous vocabulary" has its limits.

But I'm glad you agree with "code flows" in this case.

**Comment by jeffersonking** [comment]
Fixed: https://github.com/jeffersonking/sarif-vscode/commit/a5c5cd90411a238ab97f54d171768ad5a0fc1d83
________________________________
