### ISSUE TITLE
Stale results info after closing SARIF log

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-vscode-extension#277]
When closing a SARF log open in VSCode's editor, the results list properly clears, but the "result info" pane at the bottom remains.

**Comment by GabeDeBacker** [comment]
This include thread-flow steps, etc.

**Comment by Christellah** [comment]
I still encounter this problem when using the SARIF API from the WAVE VS Code extension, if I open a SARIF log with the API:

![image](https://user-images.githubusercontent.com/25352470/89954558-52c4e400-dbff-11ea-886b-93103b01c817.png)


Then close this SARIF file and re-open it using the SARIF API:

![image](https://user-images.githubusercontent.com/25352470/89954607-696b3b00-dbff-11ea-867e-673ca48825e9.png)

The previously selected error is still displayed.

**Comment by jeffersonking** [comment]
@Christellah Thanks for reporting! Fix is in PR.
