### ISSUE TITLE
Sortable results table

### ISSUE THREAD

**Issue by dgmelski** [Microsoft/sarif-vscode-extension#28]
When results are show in the "issues" window, they are organized in a tree widget which is organized by file. 

That is overly strict for a top-level summary view of results. At a minimum, results can have a priority or a severity and it is desirable to see the results sorted by severity. More generally, it may be beneficial to have a summary view that is a table with multiple columns, e.g., (brief) description, severity, file (of end point), rule id (or CWE id), and finding (true or false positive).

There are other features that may build on this feature in the future: re-prioritization of warnings based user classification of (a subset) of warnings; user filters on which warnings are in the summary view; etc.

The first issue is a summary view that sorts by priority.

**Comment by rscrivens** [comment]
The sorting would be a feature request we can make on VSCode as they're the ones controlling the Problems panel behavior and functionality. There are already a few open issues on vscode for flat list problems view and a way to group the result other then by file.

It does look like for now you can use the filter box to narrow down the severity results, I tried error, warning and info and it filtered the issues to only show that type of issue.

**Comment by michaelcfanning** [comment]
tree widget vs. flat list is an important question. maybe we just need to develop both as an option. in the short-term, we should providing an option to reorganize the tree by priority, rules, etc. 

let me loop in Jefferson king. we can add separate views as required to make progress.
