### ISSUE TITLE
2.15 release

### ISSUE THREAD

**Issue by JarLob** [microsoft/sarif-vscode-extension#286]
The latest version published in [marketplace](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer) is 2.14, meanwhile there is [2.15 available in Releases](https://github.com/microsoft/sarif-vscode-extension/releases/tag/v2.15.0).
When I downloaded the sarif-viewer-2.15.0.vsix and ran it, it failed with the error:
```
VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
```

Is it a broken release? Why is it not published in marketplace? If it is broken why it is listed in the Release section?

**Comment by JarLob** [comment]
Oddly enough, I found out that double clicking downloaded vsix extension is not the the way it is supposed to work. What works is command line `code --install-extension sarif-viewer-2.15.0.vsix`.

The question, why 2.15 released in 2019 is still unpublished remains.

**Comment by jeffersonking** [comment]
@JarLob we lost our primary contributor in 2019, and it seems 2.15 got lost in the process.

We have an upcoming 3.0 release (as you probably saw) in testing. We would love to have you give us feedback. Of course 2.14 is still supported if you need to fall back.

**Comment by JarLob** [comment]
Sure, already installed the 3.0 version. Do you still have the intention to publish 2.15?

**Comment by jeffersonking** [comment]
The current plan is to skip 2.15 and go directly to 3.0.
