### ISSUE TITLE
Plain text paragraphs are run together

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#290]
Several rule descriptions (and some result messages as well) consist of multiple paragraphs of plain text. This is explicitly permitted by the spec. For example:

> Emit arrays only if they provide additional information.
> 
> In several parts of a SARIF log file, a subset of information about an object appears in one place, and the full information describing all such objects appears in an array elsewhere in the log file. For example, each 'result' object has a 'ruleId' property that identifies the rule that was violated. Elsewhere in the log file, the array 'run.tool.driver.rules' contains additional information about the rules. But if the elements of the 'rules' array contained no information about the rules beyond their ids, then there might be no reason to include the 'rules' array at all, and the log file could be made smaller simply by omitting it. In some scenarios (for example, when assessing compliance with policy), the 'rules' array might be used to record the full set of rules that were evaluated. In such a scenario, the 'rules' array should be retained even if it contains only id information.
>
> Similarly, most 'result' objects contain at least one 'artifactLocation' object. Elsewhere in the log file, the array 'run.artifacts' contains additional information about the artifacts that were analyzed. But if the elements of the 'artifacts' array contained not information about the artifacts beyond their locations, then there might be no reason to include the 'artifacts' array at all, and again the log file could be made smaller by omitting it. In some scenarios (for example, when assessing compliance with policy), the 'artifacts' array might be used to record the full set of artifacts that were analyzed. In such a scenario, the 'artifacts' array should be retained even if it contains only location information.

The viewer runs these together into a single paragraph:

<img width="793" alt="Paragraphs bug" src="https://user-images.githubusercontent.com/11762653/86498223-c4c12800-bd39-11ea-9284-b63b2a9338ed.png">

[repro.sarif.txt](https://github.com/microsoft/sarif-vscode-extension/files/4871516/repro.sarif.txt)

**Comment by jeffersonking** [comment]
CSS `white-space: pre-line;` should solve this.
