### ISSUE TITLE
File URIs should be displayed "nicely" (decoded) to the user in the viewer..

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-vscode-extension#293]
While working with on of our interns, it was clear to me that our display of file URIs in the UI is a bit confusing to the user (and when copied, cannot be opened - at least in Windows).

The issue is that the file URIs are escaped (for example the colon in c:/  is escaped to c%3a/ etc.

The suggest is to display file URIs, well, not as URIs but there correct (non-escaped) format.

for example:
Instead of displaying "file://c%3a/users/gabrield/repos/foo.cpp" if the URI scheme is a file, show "c:\users\gabrield\repos\foo.cpp" instead. If the URI is not a file, leave it alone.

This will make more sense to most of our users and will allow the URI to be copy\pasted into things like notepad, file explorer, etc. (i.e. integrate better with the developer workflows)

**Comment by Christellah** [comment]
We noticed this issue in two places: in the Logs tab of the viewer and in the tooltip of the info tab when an error is selected, as shown on the screenshot below.

![image](https://user-images.githubusercontent.com/25352470/87190531-a373b500-c2c0-11ea-8cbd-fbd0f9e6cf8c.png)

**Comment by jeffersonking** [comment]
I think this (in technical terms) means: If the URI scheme is "file", then render `fsPath`. Otherwise maintain current behavior: render the full string (`toString`) of the URI.

**Comment by mukul-ms** [comment]
- Current status: Was able to reproduce, working on the fix. Issue found at 2 locations in the UI


-  ![image](https://user-images.githubusercontent.com/43248455/87351125-f77fd300-c526-11ea-82e6-1e74455d7726.png)

- ![image](https://user-images.githubusercontent.com/43248455/87351198-154d3800-c527-11ea-87ad-7d6df60d47d7.png)
