### ISSUE TITLE
Fix broken images in the README

### ISSUE THREAD

**Issue by garethr** [microsoft/sarif-vscode-extension#308]
## Expected

The README would have nice images of the extension in action, making it more compelling for users.

## Actual

The images are all broken. They link to assets in `resources` which was deleted in https://github.com/microsoft/sarif-vscode-extension/commit/22a23c162098801d34a3acc960e3babda341afc0.

**Comment by jeffersonking** [comment]
@garethr Thanks for reporting that. The fix is in PR.

Note we've updated the UI in the upcoming release. Screenshots for the new changes are forthcoming. The screenshots in this #309 are for the preexisting UI.
