### ISSUE TITLE
Add ability to show more then 250 issues per file in problems panel

### ISSUE THREAD

**Issue by rscrivens** [Microsoft/sarif-vscode-extension#31]
VSCode currently limits 250 diagnostics per file per DiagnosticsCollection. This prevents us from showing all of the results in a file if it's greater then 250. We currently display a custom error message after 249. A couple of possible ways to go above 250(I'm in favor of the first option):

* In the extensions DiagnosticsCollection Controller we could add an array of DiagnosticsCollections and once a collection hits the cap for a file, it then move to the next collection and fills it up. We could then establish our own limit that makes more sense for a sarif file's results, ex. 4 collections for total of 1000 results max.

* Second option would be to keep it at 249 and let the user click the custom(250th) one we add and it will cycle through to the next set of 249 for that file. This might be difficult to communicate to the user and it might get confusing to not be able to track where you are in the rotation through the errors.

**Comment by michaelcfanning** [comment]
Sort and other options should work against complete set. 

Let's focus on the our separate view that show all content for now.

**Comment by rscrivens** [comment]
closing this issue as we're tracking the sortable table in a different issue #28
