### ISSUE TITLE
SARIF Viewer fails to open (through API) when the SARIF schema needs to be updated.

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-vscode-extension#321]
The SARIF viewer is attempting to use NPX to launch the SARIF multi-tool with the "transform" argument, and that fails in a machine with just VSCode and the SARIF viewer installed as NPX cannot be found.
    
Error: spawnSync npx ENOENT  at Object.spawnSync (internal/child_process.js:1041:20)  at spawnSync (child_process.js:620:24)  at Object.execFileSync (child_process.js:647:15)  at Object.func [as execFileSync] (electron/js2c/asar.js:140:31)  at h (c:\Users\gabrield\.vscode\extensions\ms-sarifvscode.sarif-viewer-3.2020.810002-insiders\out\context.js:16:79171)  at c:\Users\gabrield\.vscode\extensions\ms-sarifvscode.sarif-viewer-3.2020.810002-insiders\out\context.js:16:80007
​[11:59 AM] Gabriel DeBacker
    
        function h(e) {
            const t = u.tmpNameSync({
                postfix: ".sarif"
            });
            return i.execFileSync("npx", ["@microsoft/sarif-multitool", "transform", e, "--force", "--pretty-print", "--output", t]), t
        }

**Comment by HenokAddis** [comment]
### Repro Versions
- OS = OS.2020
- WAVE = v3.0.200724006
- SARIF Viewer = v3.2020.715004-insiders

### Full Issue GIF
![sa_issue_build2](https://user-images.githubusercontent.com/46505299/89829743-ef0fbd80-db0f-11ea-8766-e118ce4f2da8.gif)

### More Details
When I run this with the newest WAVE and SARIF Viewer Insiders, I still see failures to upgrade. 
![image](https://user-images.githubusercontent.com/46505299/89829491-8e808080-db0f-11ea-95ba-4d5b4e39bc7c.png)

When I remove WAVE, I can no longer build the Static Analysis builds, so when I attempt to open the SARIF Viewer Pane and hit “Open SARIF file” to open a previously generated SARIF, I still hit the same issue of the Viewer not populating…but also the Problems pane seems to not work either.
![image](https://user-images.githubusercontent.com/46505299/89829508-96402500-db0f-11ea-9a37-ae1dd0904988.png)
