### ISSUE TITLE
[question] how to do path mapping in VSCode about

### ISSUE THREAD

**Issue by tim-rj** [microsoft/sarif-vscode-extension#330]
Hi Sarif team,

I have output the .sarif file, but when click the display result, can't go to the source file, how to do path mapping about this:

```

Locations: | \%SRCROOT%\common\script\ruijiecommon.py (15)
-- | --
Related: | \%SRCROOT%\common\script\ruijiecommon.py (242)


```

![企业微信截图_15973972264791](https://user-images.githubusercontent.com/51427706/90235156-69fc0f80-de53-11ea-8aa3-8f338cc508d9.png)

![企业微信截图_15973987932087](https://user-images.githubusercontent.com/51427706/90237591-18558400-de57-11ea-93b8-492578abd4f0.png)

**Comment by jeffersonking** [comment]
@tim-rj Would you be willing to upgrade to a [pre-release version](https://github.com/microsoft/sarif-vscode-extension/releases/tag/3.0.0-9) and see if you are still having this issue? Thanks!

**Comment by tim-rj** [comment]
@jeffersonking I have tried and installed it, recreate database and output .sarif file, but when i click 'Open SARIF file' button to open the .sarif file, it noticed that "Failed to upgrate  'xxx.sarif'" and nothing disappear:
![企业微信截图_15976271434255](https://user-images.githubusercontent.com/51427706/90349005-b3727780-e06a-11ea-9eec-23faf6f6be8c.png)

**Comment by jeffersonking** [comment]
@tim-rj: Thanks giving the pre-release a try. Also thanks for those screenshots. I will have a fix for you in about a day. I'll let you know it's ready.
