### ISSUE TITLE
Set suppression

### ISSUE THREAD

**Issue by sasobadovinac** [microsoft/sarif-vscode-extension#335]
Would it be possible to add the functionality to set (also unset) the suppression? The existing grouping and filtering is already very useful, but when working over a long list of issues it would be great to also have the ability to just hide (suppress) those that have been reviewed... Best would be if it would be possible to set the suppression on the individual results (issues), but also on the locations (files) and rules.

**Comment by jeffersonking** [comment]
Initially I thought you were referring to [`suppressions`](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317661) as mentioned in the SARIF spec.

However reading this issue again, I'm interpreting our suggestion as not directly related to SARIF `suppressions`. You are just referring to the general idea of being able to hide the ones you've already looked at. Is that correct?

At the risk of conflating the two concepts, we could mark your "reviewed" results as a `suppression`.* However we would probably not be able save this between VS Code sessions. We currently treat the SARIF log as read-only.

\* This is not to be confused with `suppression.kind = "underReview"` where the suppression itself is under review (as opposed to the result).

**Comment by sasobadovinac** [comment]
I was referring to the suppression as is supported by the SARIF spec yes, it could also be be done in a different way yes, but as you said it would probably be less confusing if it would be done with the existing SARIF suppression, so that there would not be a duplication of the concept, and not being able to use it over different sessions would make it much less useful.

I understand the current read-only nature of the viewer, but please rethink a bit on it, IMO having the ability to control (modify) the suppression status would in generally be very useful.
