### ISSUE TITLE
VS Code (Insiders): Error: Incorrect locale information provided

### ISSUE THREAD

**Issue by Robo210** [microsoft/sarif-vscode-extension#343]
[-1598480140096.log](https://github.com/microsoft/sarif-vscode-extension/files/5133151/-1598480140096.log)

The Console in the Developer Tools window shows these two error messages (in the attached log) appearing every few minutes.

**Comment by jeffersonking** [comment]
@Robo210: My recommendation would be to move to a newer insiders build. One of the files mentioned in the log `stringUtilities.js` has long since been removed. Thus that should fix the issue.

**Comment by Robo210** [comment]
My current extension version is
Name: Sarif Viewer
Id: ms-sarifvscode.sarif-viewer
Description: The Sarif Viewer extension visualizes the results in a Sarif file
**Version: 3.2020.430009-insiders**
Publisher: Microsoft DevLabs
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer

**Comment by jeffersonking** [comment]
Recommend installing this one: https://github.com/microsoft/sarif-vscode-extension/releases/tag/v3.2020.91001-insiders

**Comment by Robo210** [comment]
This build fixed this issue, and lots of other issues! Thanks!
