### ISSUE TITLE
Make Static Analysis Rule IDs Link out to Remediation Documentation in SARIF Viewer

### ISSUE THREAD

**Issue by Miaku** [microsoft/sarif-vscode-extension#345]
We need the rule ID to be clickable and link out the the https://aka.ms/cpp/warnings/CXXXX. SourcesCop issues do this today.

**Comment by Miaku** [comment]
![ClickableLink](https://user-images.githubusercontent.com/5658930/91780853-9d59d080-ebad-11ea-84a5-b58dd16b9856.JPG)
Example of a clickable link in SourcesCop

**Comment by jeffersonking** [comment]
If the rule contains a [helpUri property](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317848) then we will honor that as a link.

**Comment by HenokAddis** [comment]
[Bug 28913801](https://microsoft.visualstudio.com/OS/_workitems/edit/28913801): All rules in ruleset.json need clear descriptions on both OSGWiki and visible in the IDE; Need clear way to visualize TVS and MinBar rulesets (if possible)
