### ISSUE TITLE
Fill in friendly rule name and description in SARIF viewer

### ISSUE THREAD

**Issue by Miaku** [microsoft/sarif-vscode-extension#346]
The highlighted fields should be populated with good information:
![image](https://user-images.githubusercontent.com/5658930/91781191-85cf1780-ebae-11ea-9e73-2576355eea5e.png)

**Comment by jeffersonking** [comment]
If that is blank, then it indicates that rules does not have a [name](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317843) nor [shortDescription](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317845) property (or a [fullDescription](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317846) property)

**Comment by HenokAddis** [comment]
[Bug 28913801](https://microsoft.visualstudio.com/OS/_workitems/edit/28913801): All rules in ruleset.json need clear descriptions on both OSGWiki and visible in the IDE; Need clear way to visualize TVS and MinBar rulesets (if possible)
