### ISSUE TITLE
"Logs" view cannot be scrolled, so views with many log files are unusable

### ISSUE THREAD

**Issue by sivadeilra** [microsoft/sarif-vscode-extension#350]
The "Logs" view does not provide any scroll bars and does not respond to scroll wheel, etc. So if you load a lot of log files, you can't see entries that are far down the last. Nor can you remove them, unless you remove entries higher in the list so that the lower one becomes visible.

**Comment by jeffersonking** [comment]
Which version/build are you on?

________________________________

**Comment by sivadeilra** [comment]
v3.0.0-16

**Comment by jeffersonking** [comment]
Thanks. We will have a fix soon.

________________________________

**Comment by jeffersonking** [comment]
[3.0.0-17](https://github.com/microsoft/sarif-vscode-extension/releases/tag/3.0.0-17) should fix it for you.
