### ISSUE TITLE
Display non-failure results appropriately.

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#357]
When a result has `kind` equal to `"review"`, the extension displays it as "informational". But in fact, a `"review"` result should be displayed as "warning", because it means that it's an issue that requires human review to determine if there's actually a problem.

The guidance for viewers is:

- Errors: results that break/block processes.
- Warnings: items actively tracked that should always display to users but not block anything.
- Informational: low-importance items that do *not* display by default.

Here is how the viewer should treat results with a `kind` value _other than_ `"fail"`:

| `kind` value | Viewer treatment |
| --- | --- |
| `"informational"` | Informational |
| `"notApplicable"` | Informational |
| `"open"` | Warning [1] |
| `"pass"` | Informational [2] |
| `"review"` | Warning |

[1] Because this value means that the tool didn't have enough information to know if there was a problem. This is used by program correctness provers. If a prover doesn't know (for example), if a particular function can throw an exception, it might not be able to decide whether a code path is safe.

[2] Unless the extension allows you to show a green check-mark or the like for a "pass" result.

@michaelcfanning FYI

**Comment by ArlenTokatlian** [comment]
Roy mentioned we may have upcoming asks for level and kind so there may be a vested interest here. 
@lgolding to take the lead here as an initial effort. Mentioned he may know where the logic can be modified.
Note that there is a sibling work item tracked in the VS space... https://github.com/microsoft/sarif-visualstudio-extension/issues/199
