### ISSUE TITLE
Cannot load sarif files with schema from docs.oasis-open.org

### ISSUE THREAD

**Issue by FredHappyface** [microsoft/sarif-vscode-extension#363]
https://docs.oasis-open.org/sarif/sarif/v2.1.0/cos02/schemas/sarif-schema-2.1.0.json

snippet 

```json
{
	"version": "2.1.0",
	"$schema": "https://docs.oasis-open.org/sarif/sarif/v2.1.0/cos02/schemas/sarif-schema-2.1.0.json",
	"runs": [...]
}
```

changing this to https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json works 

Thanks for your time

**Comment by michaelcfanning** [comment]
Thanks for the report! This is an important problem, we'll get it fixed asap.

**Comment by jeffersonking** [comment]
@lgolding expressed interest in taking this one.

**Comment by lgolding** [comment]
PR is out: https://github.com/microsoft/sarif-vscode-extension/pull/364

**Comment by lgolding** [comment]
Version 3.0.2 of the viewer, containing this fix, is available on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer).

NOTE: If you click **Download extension** on the page, you will get the latest, 3.0.2:

![image](https://user-images.githubusercontent.com/11762653/96788321-2ae4c000-13a8-11eb-8b81-660c377c59ff.png)

At the moment, the "badge" is out of date and still says "3.0.1". Don't worry.

![image](https://user-images.githubusercontent.com/11762653/96788375-45b73480-13a8-11eb-84e5-45ddeca5d3d7.png)
