### ISSUE TITLE
Line numbers are off by one (version 3.0.2 still)

### ISSUE THREAD

**Issue by viennadd** [microsoft/sarif-vscode-extension#373]
Seems it is an opposite situation with related issue #300 

with use of [off-by-one.sarif.txt](https://github.com/microsoft/sarif-vscode-extension/files/4913792/off-by-one.sarif.txt) in #300 , the SARIF result located at line 16, but it shows at line 17.
![image](https://user-images.githubusercontent.com/3396288/109317264-80b20300-7887-11eb-8bc0-8e6be3140d9e.png)

**Comment by viennadd** [comment]
I think we don't need to convert from 0-based to 1-based at here, because SARIF line numbers are 1-based already.
https://github.com/microsoft/sarif-vscode-extension/blob/bd13e8021549fb1674795a9bd473803318dfe673/src/shared/index.ts#L118-L120

**Comment by viennadd** [comment]
seems we don't have to convert from 0-based to 1-based at here, because SARIF line numbers are 1-based already.
https://github.com/microsoft/sarif-vscode-extension/blob/bd13e8021549fb1674795a9bd473803318dfe673/src/shared/index.ts#L118-L120

**Comment by MichaelSquires** [comment]
I've been seeing this issue as well.

**Comment by eddynaka** [comment]
Hello,

sorry for the delay.
We fixed this in version 3.1.0.

The PR:
https://github.com/microsoft/sarif-vscode-extension/pull/399
