### ISSUE TITLE
Sarif panel changes unexpectedly when multiple results on a single source line

### ISSUE THREAD

**Issue by MichaelSquires** [microsoft/sarif-vscode-extension#376]
When I click on a result in the sarif panel, it takes me to the relevant source file and line number. If there are multiple results in the same source file and line number, the sarif panel will sometimes jump to another result. It makes it difficult/impossible to view the details of the result I'm interested in viewing.

**Comment by michaelcfanning** [comment]
@eddynaka  @jeffersonking 

Can we get some attention on this one?

**Comment by jeffersonking** [comment]
@MichaelSquires Do you have a repro handy for this? If not I will need to reconstruct the scenario. Thanks.

**Comment by MichaelSquires** [comment]
> @MichaelSquires Do you have a repro handy for this? If not I will need to reconstruct the scenario. Thanks.

Not at the moment. I'll put one together and get it uploaded here.

**Comment by MichaelSquires** [comment]
@jeffersonking: I was able to get a repro for this issue. 

1. Download the two files in [this gist](https://gist.github.com/MichaelSquires/8a342976534e960e4a6ed263913247ee).
2. Save them to d:\temp (if you save them somewhere else, be sure to update foo.sarif:261).
3. Open VS Code in the new directory: `code d:\temp`.
4. Click on Rules in the SARIF panel.
5. Expand C26481.
6. Click on one of the results.
7. Notice it jump to C26440 and then C26493.
8. Click on any other result in that window and it will always jump to C26440 then C26493.

At one point, the issue stopped presenting but returned after closing and reopening VS Code. Please let me know if you have any issues getting this behavior to repro.

**Comment by jeffersonking** [comment]
@MichaelSquires Thanks for your patience. #408 is likely to have addressed this issue. Optimistically closing. If not, we'd be happy to take closer look.
