### ISSUE TITLE
unable to work with urlBaseId

### ISSUE THREAD

**Issue by dev-gaur** [microsoft/sarif-vscode-extension#390]
```
"physicalLocation": {
                "artifactLocation": {
                  "uri": "path/to/myfile.json",
                  "uriBaseId": "/Users/dev-gaur/go/src/github.com/org/repo"
                },
                "region": {
                  "startLine": 1
                }
}
```

While clicking on `file.json` hyperlink on the SARIF viewer panel, I get an `unable to find file.json` dialog box. What exactly am I doing wrong here? I could not find an sample file or test case demonstrating usage of relative paths or uriBaseId.

OS: Darwin

**Comment by jeffersonking** [comment]
This might help: https://github.com/microsoft/sarif-tutorials/blob/main/samples/OriginalUriBaseIds.sarif

**Comment by dev-gaur** [comment]
Thanks @jeffersonking

**Comment by jeffersonking** [comment]
Looks like this wasn't a product issue. Closing.
