### ISSUE TITLE
Sarif report has artifact issues in it, but right panel only shows a "OpenSARIF log" button (intermittently)

### ISSUE THREAD

**Issue by huornlmj** [microsoft/sarif-vscode-extension#396]
A generated SARIF report has artifact issues in it, but when the sarif file is selected, the right panel only shows a "OpenSARIF log" button (intermittently) where the issues should be shown.  Using version v3.0.2 in VSC v1.59.1.

**Comment by jeffersonking** [comment]
#412 (v3.1.1) is likely to have fixed this. Optimistically closing. If it is still an issue please reopen and we'll take a closer look. Thanks!
