### ISSUE TITLE
SARIF Viewer causes VS Code to crash with "The window has crashed (reason: 'oom', code: '-536870904')"

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/sarif-vscode-extension#402]
Several users are reporting that launching the SARIF viewer results in:

![image](https://user-images.githubusercontent.com/36748852/137814478-3eeda785-b9ab-4357-bb0d-0dc26b568498.png)

Disabling the SARIF viewer resolves the issue.

**Comment by karsharm** [comment]
What was the issue here? Was there a fix determined?

**Comment by jeffersonking** [comment]
@karsharm The linked PR #409 should be the best explanation.
