### ISSUE TITLE
SARIF Log intermittently fails to load

### ISSUE THREAD

**Issue by jeffersonking** [microsoft/sarif-vscode-extension#405]
As quoted from @niroshan via @eddynaka:

> Very often when loading a sarif file with the plugin it fails to load with no feedback on what went wrong (that I’ve been able to find).  Loading the file multiple times will eventually load but it’s frustrating to say the least.  This problem hits different users with different frequencies.

And also:

> It’s inconsistent. The same file can fail to load a few times and then eventually work. I always select the SARIF file and let the Sarif Viewer open automatically. I don’t do it the other way around, opening the viewer first and then loading the SARIF file from there, which may behave differently. If it fails I close the Sarif Viewer and the SARIF file tabs and reload until it loads successfully. Is there a log somewhere that can give any hints on what happens?
VSCode runs on Mac (11.6) and I connect remotely to a Linux machine (Ubuntu 20.04).
File size is not big 1-2MB.
The source is always the result from CodeQL CLI, no other source. One caveat: The result from CodeQL CLI is filtered using jq to remove some test code and third party components I’m not interested in. [1]
Viewing the SARIF file itself is not such a big obstacle. We have scripts that can display the contents in various ways and the result also displays nicely in the Github UI once uploaded.
The real benefit using VSCode with the Sarif Viewer plugin is that it can link directly to the source code which facilitate fixing issues.
For the SARIF file load problem I could probably share a file with you (I don’t think there are any secrets in the file). For the other problems I can try to create a small project that demonstrates what I’m talking about.
Here is a sample SARIF file [Not copied to this issue due to privacy]. I didn’t want to spam everyone in the group with this file. I just tried loading it now with VSCode and it loaded fine twice and the third time it failed.
[1] Here is the jq filter I use, in case it somehow messes up the SARIF file.
jq 'del(
      .runs[].results[] |
      select(.locations[].physicalLocation.artifactLocation.uri |
             startswith("build/") or contains("/WebSocket.test.cpp") or startswith("src/test/")))'

**Comment by jeffersonking** [comment]
The first thing I would like to check is the debug console of VS Code. On Mac, this is `cmd+alt+i` to open it up. @niroshan, would you be able to provide me with the contents of that console during the time of the failure? Thanks!

**Comment by kuriboshi** [comment]
When it fails to load I don't see anything in the console.

**Comment by jeffersonking** [comment]
@kuriboshi Assuming you are person quoted at the top, what is the frequency of failure if you are *not* connected remotely to a Linux machine? Are you able to reproduce the issue completely locally?

**Comment by kuriboshi** [comment]
@jeffersonking Yes, that's me.  When loading locally, either on Linux or macOS, I can't repeat the problem so it does seem to be related to working with a remote project.  It would explain why it seems to happen more frequently if your remote connection is for some reason slower.  I'm using a remote connection for convenience even though the "remote" host is sitting under my desk.

**Comment by jeffersonking** [comment]
Thanks for the tip. I was unable to repro with a "remote" host on my LAN. However, I was able to repro from a coffee shop (connecting back to home). Go figure. The fix is linked and in review.

**Comment by kuriboshi** [comment]
Brilliant. Looking forward to the fix!
