### ISSUE TITLE
This extension does not load the logs from the dotnet upgrade-assistant

### ISSUE THREAD

**Issue by klacol** [microsoft/sarif-vscode-extension#411]
Hi, I am in the process of upgrading a project to .NET 6.0. I use the [dotnet upgrade-assistant](https://github.com/dotnet/upgrade-assistant) .

This assistant produces logs in the sarif-format. But they cannot be opened with this VSC-extension.

> 'c:\...\AnalysisReport.sarif' was not loaded. Version '2.1.0' and schema 'http://json.schemastore.org/sarif-2.1.0' is not supported.

Is there a plan to support this version 2.1.0?

**Comment by jeffersonking** [comment]
@klacol We support schemas ending in `2.1.0-rtm.5`. These represent the current (most common) release. Confusingly, the suffix-less `2.1.0` was considered pre-release due to a versioning mishap.

It seems dotnet upgrade-assistant is emitting the wrong schema. I believe this was addressed with a recent [PR](https://github.com/dotnet/upgrade-assistant/pull/927).

**Comment by klacol** [comment]
@jeffersonking  Thanks for your fedback.

I have changed the version string in the sarif file, that is generated by the `dotnet upgrade-assistant` from `2.1.0` to `2.1.0-rtm.5`:

![image](https://user-images.githubusercontent.com/10479772/142571690-7d7c79db-ec26-4863-b2c7-01bb932a42ac.png)

Unfortunately, the `sarif-vscode-extension` does not load this file.

![image](https://user-images.githubusercontent.com/10479772/142572020-a678ce00-a8c1-45c2-95c8-de5faf228d98.png)

I am working with a newer version of the assistant, [as of this tip](https://github.com/dotnet/upgrade-assistant/issues/940).

**Comment by jeffersonking** [comment]
@klacol I realize it's not intuitive, but the version should stay as `2.1.0`. Altogether:

```
"$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
"version": "2.1.0",
```

**Comment by klacol** [comment]
Thanks, that does not work, That was my starting point.

**Comment by jeffersonking** [comment]
Trying to see what I'm missing here.

In your screenshot:
```
"$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
"version": "2.1.0-rtm.5",
```

In my snippet:
```
"$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
"version": "2.1.0",
```
Does the latter $schema + version not work for you?
