### ISSUE TITLE
Support VS Code commands in description

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/sarif-vscode-extension#468]
We'd like to be able to add VS Code commands (i.e. `[arbitary text](command:command-goes-here)`) in the description view to help people resolve SA issues. However, react-markdown by default does not allow vscode: schemes and the command gets removed from the final rendering.

The good news is react-markdown can also be customized to allow different schemes: https://github.com/remarkjs/react-markdown#uritransformer.

**Comment by jeffersonking** [comment]
@50Wliu Apologies for not letting you know sooner, but we fixed and released this issue late Friday (version 3.3.2). Please me know if that completely addressed the issue.

**Comment by 50Wliu** [comment]
Woah, awesome! We'll let you know and close if it's resolved ^^.

**Comment by 50Wliu** [comment]
Looks like `vscode:` was added, but we also need `command:` - I can create a quick PR for that since I see where the change needs to go.
