### ISSUE TITLE
Enable extension API to open to specific SARIF result

### ISSUE THREAD

**Issue by chrishuynhc** [microsoft/sarif-vscode-extension#473]
Currently, there is not an exposed extension API that will allow other extensions to open the SARIF viewer to a specific result.  This feature would allow our extension to generate static analysis results and open the user directly to issues based on a specified result id.

**Comment by 50Wliu** [comment]
**Proposal**: Expose a new API, `async selectResult(uri: Uri, runIndex: number, resultIndex: number): void`.

**Rationale**: There is already an internal method, [panel.select](https://github.com/microsoft/sarif-vscode-extension/blob/a075d2d0f7c0613e2e023ed5e720b32d26067ae7/src/extension/panel.ts#L203), that takes in a `Result` and opens the editor/line number corresponding to that Result.
A unique Result can be looked up through the three parameters above. All in all, the full implementation of the API should look something like this:
```ts
function selectResult(uri: Uri, runIndex: number, resultIndex: number): void {
    const log = store.logs.find(log => log._uri === uri.toString());
    const result = log?.runs[runIndex]?.results?.[resultIndex];
    if (!result) return;

    panel.select(result);
}
```
