### ISSUE TITLE
Editor becomes really slow

### ISSUE THREAD

**Issue by bacebu4** [microsoft/sarif-vscode-extension#517]
Type: <b>Bug</b>

Just activate it and to nothing

Extension version: 3.3.9
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:58.115Z)
OS version: Darwin arm64 21.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|40, 86, 54|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id 5d06373c-0d2e-4131-b8c7-3efd32e41587|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590

```

</details>

**Comment by aeisenberg** [comment]
There are a number of other performance related issues that may be related. For example https://github.com/microsoft/sarif-vscode-extension/issues/472.

As suggested [here](https://github.com/microsoft/sarif-vscode-extension/issues/472#issuecomment-1414041394), could you please try disabling the extension's GitHub Code Scanning feature to see if the symptoms stop? This can be done in the extension settings:

![image](https://github.com/microsoft/sarif-vscode-extension/assets/363559/e383a863-322b-4063-b36c-f59c5cf4b64a)

**Comment by bacebu4** [comment]
> There are a number of other performance related issues that may be related. For example #472.
> 
> As suggested [here](https://github.com/microsoft/sarif-vscode-extension/issues/472#issuecomment-1414041394), could you please try disabling the extension's GitHub Code Scanning feature to see if the symptoms stop? This can be done in the extension settings:
> 
> ![image](https://user-images.githubusercontent.com/363559/256874071-e383a863-322b-4063-b36c-f59c5cf4b64a.png)

After couple of seconds and reloads it actually helped, but not instantly after the reload. Thanks!

**Comment by bacebu4** [comment]
Though after every VSCode reload it takes about 30 seconds for issue to go
