### ISSUE TITLE
command 'sarif.toggleDrift' not found

### ISSUE THREAD

**Issue by jsoref** [microsoft/sarif-vscode-extension#529]
<details><summary>Version info</summary>

```
Version: 1.83.0 (Universal)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:15.449Z (1 wk ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

```
MS-SarifVSCode.sarif-viewer v3.4.2
```
</details>

![image](https://github.com/microsoft/sarif-vscode-extension/assets/2119212/baf8acfa-ca9c-47bf-9cee-94ec19523b04)

![image](https://github.com/microsoft/sarif-vscode-extension/assets/2119212/67b1faf9-0e62-4231-897a-375a1f1f247b)

Command 'SARIF: Toggle Drift' resulted in an error

**Comment by aeisenberg** [comment]
That's odd. I don't know what this command is supposed to do. Regardless, there's no implementation for it. I put up a PR to remove it.

https://github.com/microsoft/sarif-vscode-extension/pull/530

**Comment by jsoref** [comment]
@aeisenberg: will this issue be closed automatically at some point?
