### ISSUE TITLE
VS Code lags to the point of being unusable in large repos

### ISSUE THREAD

**Issue by jefgen** [microsoft/sarif-vscode-extension#535]
Type: <b>Bug</b>

When this extension is enabled for a really large repo, editing simple markdown files becomes so slow that VS Code is no longer even usable.

I used the [Extension Bisect](https://github.com/microsoft/vscode/wiki/Performance-Issues#consuming-cpu) feature to narrow down which extension was causing the issue, and it appears to be coming from this one only.

Looking in Process Explorer, I see lots of `rg.exe` processes being spun up when editing a markdown file. I'm not sure why so many are being created.

Steps to repo:
- Clone and open a large repo.
- Try to edit a simple markdown file in the repo.
- VS Code becomes laggy to the point of being unusable.

Extension version: 3.4.2
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.25978
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (13.30GB free)|
|Process Argv|--crash-reporter-id 8d1aab88-1037-441d-bd02-8a56ae6607cf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30859502
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmpsinfo:30842941
dsvsc015:30845448
pyreplss2:30864989
pythontbext0:30864172

```

</details>

**Comment by jefgen** [comment]
Possibly related issue #527

**Comment by damyanp** [comment]
+1 on this (was about to file essentially the same issue)

**Comment by stmillMSFT** [comment]
This issue is absolutely still repro, btw. I'm having this issue too. Same thing: no SARIF files in repo, and not even that big of a repo, but about a million rg.exe instances are spawned, and I can't type anymore. Even when markdown files aren't open. Mostly .ts and .tsx. Since this extension seems to have been pushed out via group policy for some unknown reason, please address as a higher severity; this is making internal work miserable.

**Comment by 50Wliu** [comment]
@stmillMSFT could you create a new issue for what you're seeing, please?
