### ISSUE TITLE
Remapping dialog doesn't prompt for original file path

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-vscode-extension#58]
When we go to remap a SARIF file, the file open dialog comes up with no additional information on what file we should be looking for.

**Comment by rscrivens** [comment]
the Ux for file remapping has been changed. with the check in for #50 adding a way to set rootpaths to the settings. These changes will be available next release.

**Comment by rscrivens** [comment]
The latest changes have been pushed out in update 2.2.0 , included in the change is one that addresses this issue. Closing this issue, if you still find problems with the new changes feel free to add additional details and reopen.
