### ISSUE TITLE
Suggestion: don't ask for mapping when file contents are embedded

### ISSUE THREAD

**Issue by lukecartey** [Microsoft/sarif-vscode-extension#61]
The following message appears whenever a SARIF file is loaded for which we don't have a current mapping:

![image](https://user-images.githubusercontent.com/5377966/42288321-19cf456a-7fb2-11e8-9799-616d929a8ea5.png)

However, this is confusing when the SARIF file contains embedded file content. In that case, if you click "Later", all the files will be loaded from the SARIF file itself i.e. the mapping wasn't necessary. In this case, it seems like the extension should not pop-up the mapping request at all.

**Comment by rscrivens** [comment]
This dialog should only show up if it can't find the files, including checking if they're embedded. My guess is there is at least 1 file that isn't embedded that the extension is asking input for. It should become clearer which files it can't find with the newest changes, which will show the actual file path it's trying to find. If you still run into this issue after I push out the next update, I'll look into it further.

**Comment by rscrivens** [comment]
The latest set of changes have been pushed out in update 2.2.0 , could you give it a try and see if the changes to the remapping addresses this issue?
