### ISSUE TITLE
End column should be exclusive, not inclusive

### ISSUE THREAD

**Issue by lukecartey** [Microsoft/sarif-vscode-extension#62]
The v2 spec says:

> 3.22.8 endColumn property
When a region object represents a text region, it MAY contain a property named endColumn whose value is an integer whose value is one greater than the column number of the last character in the region.

Currently, the extension treats the endColumn as the column number of the last character in the region, so the highlighted range is one greater than it should be.

Note: endColumn was inconsistently defined in v1 and earlier versions of the v2 spec, which is probably why this confusion occurred.

**Comment by rscrivens** [comment]
Thanks for the bug @lukecartey I'll investigate, should be a relatively easy fix.

**Comment by michaelcfanning** [comment]
Thanks for tackling this, Rusty. Put me on the PR and I'll see if I can start ramping up a bit more on this code base.

**Comment by michaelcfanning** [comment]
Thanks for addressing this. My apologies for failing to notice this was scheduled for the 2.3 milestone.

**Comment by rscrivens** [comment]
Fix has been merged into dev branch, it'll be in update 2.3.0, releasing this week.
