### ISSUE TITLE
Rebasing is cumbersome

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-vscode-extension#71]
We lost the file picker, can you please find a way to return it? I was unable to manually update the file path for the SDK SDV tests. The process was cumbersome.

Please follow up with the VS Code team on the failure to provide a mechanism to add a title to the file picker. That is either possible with their API or it is a bug they should fix. It is a significant issue is a file picker comes up with no useful title for users.

**Comment by rscrivens** [comment]
Thanks for the feedback. I'll add this to the backlog to investigate in a future milestone. An initial idea to discuss:

The vscode team has a proposed api that gives an inputbox with more control. It has a way to set buttons, so maybe one option is to keep the current inputbox look and add in a button to pop open an open file picker to it, then once the file is selected we can update the string in the input box with the updated file location.

If we go this route we could also add a button to skip mapping the current file and move to the next one, this would allow a user to selectively decide not to map a file vs. the current behavior where once you hit escape it stops asking the user if it can't map a file(you're still able to manually remap a result via the code action light bulb in the editor).

**Comment by michaelcfanning** [comment]
Makes sense. If VS Code is close to shipping a relevant improvement, let's wait for it.

In the meantime, thanks for your offline comments on the feature. I was confused by the UI because it only verifies the path looks valid. It doesn't actually confirm whether the file exists until you hit enter. We might consider doing the file existence check right away. If it exists on disk, shouldn't we just accept it?

After discovering that the file doesn't exists, I see your guidance about providing a file:// uri. I actually tried to update the file path in the first UI (where this guidance doesn't exist).

**Comment by michaelcfanning** [comment]
Note that uriBaseId use greatly simplifies this problem, you just need to query the user to resolve the set of unique uriBaseIds encountered in the file.

**Comment by rscrivens** [comment]
Regarding the file existence check on initial value, we do set a validator, but vscode handles when to validate and what to do when we return a message for invalid data. When I checked this in it was working correctly where it would show the invalid redbox and message on the initial value. But it looks like vscode made a change that while it still validates the initial value it no longer shows the invalid message and redbox untill a user hit's enter or changes the value: https://github.com/Microsoft/vscode/issues/52908

**Comment by rscrivens** [comment]
in checkin #85 I've updated the user input to use the more customizable input dialog. I've added a button to open a file picker, added a skip to next mapping button, fixed the red box not showing on first load, and removed the file:/// from the UI entirely so the user now just needs to put in a "normal" path ex. d:/folder/file.ext
