### ISSUE TITLE
Automate release steps when pulling Dev into Master branch

### ISSUE THREAD

**Issue by rscrivens** [microsoft/sarif-vscode-extension#77]
A task to cover automating the release steps when pulling Dev into Master branch.

Some tasks to automate include:
* Creating a tag based off of the version
* Creating a release based off the version, (assigned to the tag)
* Attaching the vsix to the release
* Packaging the vsix
* Publishing the vsix to the marketplace
* Running the test suite

**Comment by jeffersonking** [comment]
Complete as of 5ec98ffff16b706e3837ff90026f52466ba04182 (Sept 2020) except for auto-publish to the Marketplace. Prefer to keep it manual at the moment. Also, having issues with DevOps not allowing me to obtain certain PAT scopes.
