### ISSUE TITLE
Code flow items get ugly with a long file path

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [Microsoft/sarif-vscode-extension#81]
Causes the location text to wrap. Suggest ellipsis truncation if possible (but keep the line # visible)

**Comment by rscrivens** [comment]
good point, I'll look into adding a truncation for the file name to keep it cleaner.

**Comment by rscrivens** [comment]
Added an ellipse, and tweaked the layout to better show the code flows with larger file names and when the window width is reduced
