### ISSUE TITLE
Whole-line code flow location don't highlight

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [Microsoft/sarif-vscode-extension#82]
Sample attached. Choose result that begins with "Attackers are able..."
The first two code flow locations are whole-line, i.e. startLine and endLine are the only region properties and they have the same value.
[FortifyDemo.fpr.v2 .sarif.txt](https://github.com/Microsoft/sarif-vscode-extension/files/2328920/FortifyDemo.fpr.v2.sarif.txt)

**Comment by EasyRhinoMSFT** [comment]
[ContentFileHandlingController.cs.txt](https://github.com/Microsoft/sarif-vscode-extension/files/2328995/ContentFileHandlingController.cs.txt)

**Comment by rscrivens** [comment]
let me double check on the latest I might have fixed this with my most recent changes. If not it should be a quick fix.

**Comment by rscrivens** [comment]
I checked with the latest in Dev branch and this looks like it's fixed. Closing, feel free to reopen if it still repos for you after the next released update (or if you run a build from the dev branch).
