### ISSUE TITLE
Source file opens in both group panes and Explorer UI is not the active tab

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [Microsoft/sarif-vscode-extension#84]
1. Open the attached log
2. Select the first result (and do the rebase if necessary)
3. Click a codeflow step
4. Select the second result

The source file for the second result opens in both group panes and the Explorer UI is not the active tab in the right pane.

[FortifyDemo.fpr.v2 .sarif.txt](https://github.com/Microsoft/sarif-vscode-extension/files/2329003/FortifyDemo.fpr.v2.sarif.txt)
[ContentFileHandlingController.cs.txt](https://github.com/Microsoft/sarif-vscode-extension/files/2329004/ContentFileHandlingController.cs.txt)

**Comment by EasyRhinoMSFT** [comment]
The source file opens on both sides after a number of other usage sequences, but usually the Explorer UI ends up as the active tab. There is an ugly transition though, where I see the source file for a split second before it switches to the tool window.

**Comment by rscrivens** [comment]
unfortunately I don't think this is something I can control, as the problems panel controls opening the source file when you click on a result in it. And so it's deciding to open the file on the right panel (because it last had focus) even though the file is already open on the left panel.
