### ISSUE TITLE
No README documentation for building the viewer from source to local vsix for installation

### ISSUE THREAD

**Issue by cfaucon** [Microsoft/sarif-vscode-extension#86]
There is no documentation on how to build this viewer locally after a git clone, and how to produce a package that can be installed locally to VSCode.

**Comment by rscrivens** [comment]
I have all the build/install info in the Contributing file here: https://github.com/Microsoft/sarif-vscode-extension/blob/master/CONTRIBUTING.md

Seemed to make the most sense there as the readme is also what gets shown on the vs extension's page.
